#!/usr/bin/env python3

##
## EPITECH PROJECT, 2024
## Pandoc
## File description:
## funcTest
##

import unittest
import subprocess

def run_pandoc_with_args(args):
    process = subprocess.run(['./mypandoc'] + args, capture_output=True, text=True)
    return process.stdout, process.stderr, process.returncode

class CommandLineArgs(unittest.TestCase):

    def test_error_if_no_arguments(self):
        stdout, stderr, returncode = run_pandoc_with_args([])
        self.assertEqual(stdout, '')
        self.assertIn('USAGE: ./mypandoc -i ifile -f oformat [-o ofile] [-e iformat]', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_1_argument(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i'])
        self.assertEqual(stdout, '')
        self.assertIn('USAGE: ./mypandoc -i ifile -f oformat [-o ofile] [-e iformat]', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_2_arguments(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'input'])
        self.assertEqual(stdout, '')
        self.assertIn('USAGE: ./mypandoc -i ifile -f oformat [-o ofile] [-e iformat]', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_3_arguments(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'testFiles/validFile/JsonFile.json', '-f'])
        self.assertEqual(stdout, '')
        self.assertIn('USAGE: ./mypandoc -i ifile -f oformat [-o ofile] [-e iformat]', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_5_arguments(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'input', '-f', 'json', '-o'])
        self.assertEqual(stdout, '')
        self.assertIn('USAGE: ./mypandoc -i ifile -f oformat [-o ofile] [-e iformat]', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_7_arguments(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'testFiles/validFile/JsonFile.json', '-f', 'xml', '-o', 'output', '-e'])
        self.assertEqual(stdout, '')
        self.assertIn('USAGE: ./mypandoc -i ifile -f oformat [-o ofile] [-e iformat]', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_more_than_8_arguments(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'testFiles/validFile/JsonFile.json', '-f', 'xml', '-o', 'output', '-e', 'xml', '-a'])
        self.assertEqual(stdout, '')
        self.assertIn('USAGE: ./mypandoc -i ifile -f oformat [-o ofile] [-e iformat]', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_missing_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-f', 'json'])
        self.assertEqual(stdout, '')
        self.assertIn('i is missing.', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_missing_format(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'testFiles/validFile/JsonFile.json'])
        self.assertEqual(stdout, '')
        self.assertIn('f is missing.', stderr)
        self.assertEqual(returncode, 84)

    def test_error_if_cannot_open_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'invalidInput', '-f', 'json'])
        self.assertEqual(stdout, '')
        self.assertIn('file not found', stderr)
        self.assertEqual(returncode, 84)

    def test_invalid_format(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'testFiles/validFile/JsonFile.json', '-f', 'invalidFormat'])
        self.assertEqual(stdout, '')
        self.assertIn('invalid arguments', stderr)
        self.assertEqual(returncode, 84)

    def test_valid_json_format(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/validFile/JsonFile.json', '-f', 'json'])
        self.assertNotEqual(stdout, '')
        self.assertEqual(stderr, '')
        self.assertEqual(returncode, 0)

    def test_valid_xml_format(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/validFile/JsonFile.json', '-f', 'xml'])
        self.assertNotEqual(stdout, '')
        self.assertEqual(stderr, '')
        self.assertEqual(returncode, 0)

    def test_valid_md_format(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/validFile/JsonFile.json', '-f', 'markdown'])
        self.assertNotEqual(stdout, '')
        self.assertEqual(stderr, '')
        self.assertEqual(returncode, 0)

    def test_invalid_json_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/invalidFile/JsonFile.json', '-f', 'xml'])
        self.assertEqual(stdout, '')
        self.assertIn('invalid file content', stderr)
        self.assertEqual(returncode, 84)

    def test_invalid_xml_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/invalidFile/XmlFile.xml', '-f', 'json'])
        self.assertEqual(stdout, '')
        self.assertIn('invalid file content', stderr)
        self.assertEqual(returncode, 84)

    def test_invalid_md_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/invalidFile/MdFile.md', '-f', 'json'])
        self.assertEqual(stdout, '')
        self.assertIn('invalid file content', stderr)
        self.assertEqual(returncode, 84)

    def test_valid_json_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/validFile/JsonFile.json', '-f', 'xml'])
        self.assertNotEqual(stdout, '')
        self.assertEqual(stderr, '')
        self.assertEqual(returncode, 0)

    def test_valid_xml_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/validFile/XmlFile.xml', '-f', 'json'])
        #self.assertNotEqual(stdout, '')
        self.assertEqual(stderr, '')
        self.assertEqual(returncode, 0)

    def test_valid_md_input_file(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/validFile/MdFile.md', '-f', 'json'])
        #self.assertNotEqual(stdout, '')
        self.assertEqual(stderr, '')
        self.assertEqual(returncode, 0)

    def test_valid_4_arguments(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-i', 'tests/testFiles/validFile/JsonFile.json', '-f', 'markdown'])
        self.assertNotEqual(stdout, '')
        self.assertEqual(stderr, '')
        self.assertEqual(returncode, 0)

    def test_invalid_flags(self):
        stdout, stderr, returncode = run_pandoc_with_args(['-a', 'testFiles/validFile/JsonFile.json', '-f', 'json'])
        self.assertEqual(stdout, '')
        self.assertIn('invalid arguments', stderr)
        self.assertEqual(returncode, 84)

if __name__ == '__main__':
    unittest.main(verbosity=2)